### ISSUE TITLE
Blender 2.80 support

### ISSUE THREAD

**Issue by ghost** [zeffii/set_arbitrary_vcols#2]
Will this addon be ported over to Blender 2.80? It really speeds up my workflow. Thanks!

**Comment by zeffii** [comment]
sure, i'll have a look at this later

**Comment by ghost** [comment]
Hi, any update on this?

**Comment by zeffii** [comment]
yep, sorry

### set_arbitrary_vcols.py

```python
import bpy
import random

bl_info = {
    'author': 'zeffii',
    'category': '3D View',
    'description': 'Set vcols by selecting verts/edges/faces and running this operator',
    'name': 'Set Vertex Colors',
    "blender": (2, 91, 0)
}


def set_verts_colors(new_color):

    # must switch to Object Mode briefly to get the new set of selected elements
    # and then change the vertex_color layer
    bpy.ops.object.mode_set(mode='OBJECT')
    obj = bpy.context.active_object

    mesh = obj.data
    color_layer = mesh.vertex_colors.active  
    selected = set(v.index for v in obj.data.vertices if v.select)

    i = 0
    for poly in mesh.polygons:
        for loop_index in poly.loop_indices:
            vidx = mesh.loops[loop_index].vertex_index            
            if vidx in selected:
                color_layer.data[i].color = new_color
            i += 1

    # set to vertex paint mode to see the result
    # bpy.ops.object.mode_set(mode='VERTEX_PAINT')
    bpy.ops.object.mode_set(mode='EDIT')


class BSEVtexSetter(bpy.types.Operator):
    bl_idname = "object.vertex_color_setter"
    bl_label = "Set VCols of any Geometry"
 
    def draw(self, context):
        self.layout.prop(context.scene, 'BSE_new_color')
 
    def execute(self, context):
        set_verts_colors(context.scene.BSE_new_color)
        return {'FINISHED'}
 
    def invoke(self, context, event):
        return context.window_manager.invoke_props_dialog(self)
 
 
def register():
    bpy.types.Scene.BSE_new_color = bpy.props.FloatVectorProperty(
        name="Color to work with", subtype='COLOR', min=0.0, max=1.0, size=4
    )
    bpy.utils.register_class(BSEVtexSetter)

def unregister():
    bpy.utils.unregister_class(BSEVtexSetter)
    del bpy.types.Scene.BSE_new_color

if __name__ == "__main__":
    register()
```

**Comment by zeffii** [comment]
hit `F3`  and type `object.vertex_color_setter` and it will auto suggest it in future (for rest of Blender session).

that's all i can do,  if you want to make it more user friendly, you should take time to investigate python.

**Comment by ghost** [comment]
Says "cannot find object.vertex_color_setter".

**Comment by zeffii** [comment]
all i did was update the version of Blender it can support and added the alpha channel to vertexcolor popup.

i didn't update the repository code, so be sure to use the snippet above.

**Comment by zeffii** [comment]
works fine here : /

**Comment by ghost** [comment]
I did copy paste, it installed fine, but nothing shows up when typing in the search bar.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/101247449-0b1c1800-371a-11eb-8bba-2960f915d4a6.png)
![image](https://user-images.githubusercontent.com/619340/101247462-1c652480-371a-11eb-9114-e04c4103c026.png)
![image](https://user-images.githubusercontent.com/619340/101247471-25ee8c80-371a-11eb-890a-6dffdea1c13e.png)

i don't know @smokingbenji

**Comment by ghost** [comment]
So it works fine in 2.80, but not in 2.91, however looking at the defined Blender version, it should work there as well. What version are you using?

**Comment by zeffii** [comment]
2.92  https://builder.blender.org/download/

**Comment by ghost** [comment]
Finally figured it, I was searching in the "wrong" "menu". It's not available in "Menu search" which is enabled by default, but instead you need to use "Operator search" as was default in 2.79. I'm sorry for your trouble. Resolved.
